### ISSUE TITLE
本软件与机场配置文件 merge 问题

### ISSUE THREAD

**Issue by IcyDesert** [chenx-dust/HITsz-Connect-for-Windows#6]
# 使用环境
- Windows 11 23H2
- Clash Verge Rev 2.0.3-alpha
- HITsz Connect for Windows 1.1.3-preview

# 期望
我希望将机场配置与本软件的代理配置进行合并，实现在校外既能使用机场，也能用上校园网

# 实现
根据 https://github.com/chenx-dust/HITsz-Connect-for-Windows/blob/master/docs/ADVANCED_USAGE.md ，在机场提供的 yaml 文件中，我修改了如下三处
```yaml
proxies:
  - {name: 🖥 HITsz Connect, type: socks5, server: 127.0.0.1, port: 11080, udp: true} <<<
  - {name: 🇭🇰 香港S01, server:机场提供, .....}
  - ....

proxy-groups:
  - name: 🏫 校园网 <<<
    type: select <<<
    proxies: <<<
      - DIRECT <<<
      - 🖥 HITsz Connect <<<
  - name: 🔰 选择节点
    type: select
    proxies:
      - 🇭🇰 香港S01
      - ...

rules:
  - DOMAIN,vpn.hitsz.edu.cn,DIRECT <<<
  - DOMAIN-SUFFIX,hitsz.edu.cn,🏫 校园网 <<<
  - IP-CIDR,10.0.0.0/8,🏫 校园网,no-resolve <<<
  # 可在此添加其它你需要代理的 ip 段，如课程中心 <<<
 - DOMAIN,app.biliapi.net,🌏 爱奇艺&哔哩哔哩
 - ...
```

# 问题表现
`重新激活订阅`后，代理组全部失效。
![Image](https://github.com/user-attachments/assets/dd3b3279-a0bc-4afe-94b8-454117330532)

# 补充信息
我在机场原有的 yaml 中，并未发现代理服务器使用 11080 端口。
如果需要全部 yaml 信息，我可以私聊提供。
